# Generated by Django 6.0.2 on 2026-03-18 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_created_by'),
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='prescription',
        ),
        migrations.AddField(
            model_name='consultation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultations_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consultation', to='appointments.appointment'),
        ),
    ]
