# Generated by Django 6.0.2 on 2026-03-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_deleted_at_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('receptionist', 'Receptionist')], default='receptionist', max_length=20),
        ),
    ]
